INSERT INTO USERDATA (ID, USER_NAME) VALUES (101, 'Tom');
INSERT INTO USERDATA (ID, USER_NAME) VALUES (102,'Andrew');
INSERT INTO USERDATA (ID, USER_NAME) VALUES (103,'Tony');
INSERT INTO USERDATA (ID, USER_NAME) VALUES (104,'Bob');
INSERT INTO USERDATA (ID, USER_NAME) VALUES (105,'Sam');
